version: "3.9"

services:
  web:
    image: localhost/filmes_php:latest
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:15
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
    ports:
      - "5432:5432"

  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
